#--------------------------------------------------------------------------------------------------
# vlc-android
#--------------------------------------------------------------------------------------------------

jobs:
- job: vlcAndroid
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      cd vlc-android
      ls -la
      docker build -t image .
      cd -
      docker save image > vlc-android.tar
  - publish: $(System.DefaultWorkingDirectory)/vlc-android.tar
    artifact: vlc-android
