#--------------------------------------------------------------------------------------------------
# debian_vlc_android
#--------------------------------------------------------------------------------------------------

jobs:
- job: debian_vlc_android
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker build -t image debian-vlc-android
      docker save image > debian-vlc-android.tar
  - publish: $(System.DefaultWorkingDirectory)/debian-vlc-android.tar
    artifact: debian-vlc-android
