#--------------------------------------------------------------------------------------------------
# debian_vlc_android
#--------------------------------------------------------------------------------------------------

jobs:
- job: ubuntu_amd64_18_04
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      cd script
      sh build.sh -c ubuntu_amd64_18_04 -i ubuntu_amd64_18_04 amd64/ubuntu:18.04

#- job: debian_vlc_android
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker build -t debian-vlc-android debian-vlc-android
#      docker save debian-vlc-android > debian-vlc-android.tar
#  - publish: $(System.DefaultWorkingDirectory)/debian-vlc-android.tar
#    artifact: debian-vlc-android
