#--------------------------------------------------------------------------------------------------
# vlc-android
#--------------------------------------------------------------------------------------------------

jobs:
- job: vlcAndroid
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker build --tag image vlc-android
      docker save image > vlc-android.tar
  - publish: $(System.DefaultWorkingDirectory)/vlc-android.tar
    artifact: vlc-android
